#### Повторение

In [1]:
import numpy as np

In [2]:
v1 = np.array([-1, 2, -7, 9]).T
v2 = np.array([2, 8, 2, -1]).T

In [3]:
np.dot(v1, v2)

-9

In [4]:
A = np.array([[1, 1], [1, 2]])
A_G = A.T @ A
A_G

array([[2, 3],
       [3, 5]])

In [5]:
B = np.array([[1, 2], [3, 7]])
B_inv = np.linalg.inv(B)
B_inv

array([[ 7., -2.],
       [-3.,  1.]])

In [6]:
n1 = np.array([2, 10, -2])
n2 = np.array([3, 2, -2])
n3 = np.array([8, 14, -6])
C = np.array([n1, n2, n3]).T
print(np.linalg.matrix_rank(C))


2


In [8]:
C.T

array([[ 2, 10, -2],
       [ 3,  2, -2],
       [ 8, 14, -6]])