#### Практика

In [2]:
import numpy as np

In [3]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
print(A)

[[ 8  6 11]
 [ 7  5  9]
 [ 6 10  6]]


In [4]:
# обратная матрица
A_inv = np.linalg.inv(A)
print(A_inv)

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


In [14]:
# В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.
print(round(A_inv[1,0],3))

0.375


In [21]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
B = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(B))

4


In [24]:
#Найдите матрицу Грама системы векторов. В качестве ответа запишите элемент из четвёртого столбца первой строки.
B_G = B.T@B
B_G
B_G[0, 3]

-35

In [28]:
B_G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [27]:
round(np.linalg.det(B_G))

3716648

In [ ]:
# Найдите обратную матрицу к матрице Грама
# В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [32]:
B_G_inv = np.linalg.inv(B_G)
print(B_G_inv)
print(round(B_G_inv[2, 0],3))

[[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
-0.026
